# Generated by Django 3.0.3 on 2020-03-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BsuClientlist',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('addr1', models.CharField(blank=True, max_length=40, null=True)),
                ('addr2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('zip', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('main_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('after_hours_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ceo_mgr', models.CharField(blank=True, max_length=40, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bsu_clientlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BsuEformsschemadetail',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('loanid', models.IntegerField(blank=True, null=True)),
                ('pageid', models.IntegerField(blank=True, null=True)),
                ('groupid', models.IntegerField(blank=True, null=True)),
                ('lineid', models.IntegerField(blank=True, null=True)),
                ('fieldtype', models.CharField(blank=True, max_length=10, null=True)),
                ('fieldvalue', models.CharField(blank=True, max_length=2000, null=True)),
                ('fieldattr', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'db_table': 'bsu_eformsschemadetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BsuEformsschemamaster',
            fields=[
                ('loanid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('loantitle', models.CharField(blank=True, max_length=50, null=True)),
                ('loandesc', models.CharField(blank=True, max_length=1000, null=True)),
                ('lastmodified', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bsu_eformsschemamaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BsuOfficeusers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('failedremain', models.IntegerField(blank=True, null=True)),
                ('forceremain', models.IntegerField(blank=True, null=True)),
                ('priorlogin', models.CharField(blank=True, max_length=20, null=True)),
                ('failedlogin', models.CharField(blank=True, max_length=20, null=True)),
                ('pwchange', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bsu_officeusers',
                'managed': False,
            },
        ),
    ]
